### PR TITLE
Stack Reset Implementation

### PR DESCRIPTION
**Pull request by RevanthRajashekar**

### CODE REVIEW

**Review by AndrzejJakowski — COMMENTED** [review]
nitpick: "receive" is mispelled in commit title

**Comment by AndrzejJakowski** [comment]
Thx for sending. Other than small nitpick looks good to me.

**Comment by RevanthRajashekar** [comment]
Commit messages corrected.

**Comment by AndrzejJakowski** [comment]
Awesome thank you! merging....

**Pull request merged**
